### ISSUE TITLE
Sample Design

### ISSUE THREAD

**Issue by SeoHyunAhn** [Purdue-ACM-SIGAPP/StudyTables-android#9] opened 2017-01-19 04:10 UTC
[iPhone 67 – 1.pdf](https://github.com/Purdue-ACM-SIGAPP/StudyTables-android/files/715687/iPhone.67.1.pdf)
[iPhone 67 – 2.pdf](https://github.com/Purdue-ACM-SIGAPP/StudyTables-android/files/715688/iPhone.67.2.pdf)
[iPhone 67 – 3.pdf](https://github.com/Purdue-ACM-SIGAPP/StudyTables-android/files/715689/iPhone.67.3.pdf)
[iPhone 67 – 4.pdf](https://github.com/Purdue-ACM-SIGAPP/StudyTables-android/files/715690/iPhone.67.4.pdf)
[iPhone 67 – 5.pdf](https://github.com/Purdue-ACM-SIGAPP/StudyTables-android/files/715691/iPhone.67.5.pdf)
[iPhone 67 – 6.pdf](https://github.com/Purdue-ACM-SIGAPP/StudyTables-android/files/715692/iPhone.67.6.pdf)
[iPhone 67 – 7.pdf](https://github.com/Purdue-ACM-SIGAPP/StudyTables-android/files/715693/iPhone.67.7.pdf)
[iPhone 67 – 8.pdf](https://github.com/Purdue-ACM-SIGAPP/StudyTables-android/files/715694/iPhone.67.8.pdf)
[iPhone 67 – 9.pdf](https://github.com/Purdue-ACM-SIGAPP/StudyTables-android/files/715696/iPhone.67.9.pdf)
[iPhone 67 – 10.pdf](https://github.com/Purdue-ACM-SIGAPP/StudyTables-android/files/715695/iPhone.67.10.pdf)

**Comment by SeoHyunAhn** [comment] 2017-01-19 04:16
![sample 1](https://cloud.githubusercontent.com/assets/22055380/22093494/24426652-ddd4-11e6-8ca4-1cc22df916ca.png)

Same as above

**Comment by vidia** [comment] 2017-02-09 22:15
Now this is a duplicate of the updated #12

**Closed by vidia** 2017-02-09 22:15 UTC
Labels: duplicate
